# Generated by Django 4.1.3 on 2022-11-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SKP')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SKP',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('User', 'User'), ('Station', 'Station')], default='skp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='skp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.skp'),
        ),
    ]
