# Generated by Django 4.1.3 on 2022-11-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0003_alter_skp_slug'),
        ('Auth', '0002_alter_user_skp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=790541511, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='skp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SKP.skp'),
        ),
    ]
