# Generated by Django 4.1.3 on 2022-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_skp_user_type_user_skp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skp',
            name='image',
            field=models.ImageField(upload_to='skp'),
        ),
    ]
