# Generated by Django 4.1.3 on 2022-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_skp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('User', 'User'), ('Station', 'Station'), ('Admin', 'Admin')], max_length=255),
        ),
    ]
