# Generated by Django 4.0.4 on 2022-11-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('station', 'station'), ('admin', 'admin')], max_length=255),
        ),
    ]
