# Generated by Django 4.1.3 on 2022-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='desc',
            field=models.CharField(default='Lorem ipsum', max_length=255),
            preserve_default=False,
        ),
    ]
