# Generated by Django 4.1.3 on 2022-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
