# Generated by Django 4.1.3 on 2022-11-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='image',
            field=models.ImageField(default='', upload_to='SKP'),
            preserve_default=False,
        ),
    ]
