# Generated by Django 4.1.3 on 2022-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0002_skp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skp',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
