# Generated by Django 4.1.3 on 2022-11-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0002_skp_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skp',
            name='city',
            field=models.CharField(db_collation='und-x-icu', max_length=255),
        ),
    ]
