# Generated by Django 4.1.3 on 2022-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0003_alter_skp_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddField(
            model_name='skp',
            name='vehicles',
            field=models.ManyToManyField(blank=True, null=True, to='SKP.vehicles'),
        ),
    ]
