# Generated by Django 4.1.3 on 2022-11-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0004_vehicles_skp_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='address',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skp',
            name='community',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skp',
            name='email',
            field=models.EmailField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skp',
            name='nip',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skp',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skp',
            name='postal_code',
            field=models.CharField(default=-333, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skp',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='SKP.vehicles'),
        ),
    ]
