# Generated by Django 4.1.3 on 2022-11-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKP', '0005_skp_address_skp_community_skp_email_skp_nip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skp',
            name='nip',
            field=models.CharField(max_length=10),
        ),
    ]
